### ISSUE TITLE
Question about state (data) handling

### ISSUE THREAD

**Issue by Ha02hen** [CenterForTheBuiltEnvironment/comfort-dash#18]
After discussing the data management part with @Echo11ovo , we identified a few issues:

When all webpages use the same storage method, the following problems may arise:
1. If only the URL is used for storage, switching from `127.0.0.1:8050/single?***` to `127.0.0.1:8050/compare?***` will result in the loss of the page state saved in the URL `127.0.0.1:8050/single?***`
2. If we rely solely on local storage, it becomes impossible to share the saved page state via a URL

To address these issues, we have proposed two solutions:
1. Add a floating "Share" button to the page. When a user clicks this button, the content stored in local storage is parsed and added to the URL. This way, other users accessing the page via this URL can see the saved page state. Normally, the page state won't be explicitly displayed in the URL, but it will be included when generating a shareable link
2. Change the way the URL data is retrieved to prioritize fetching data from local storage. If there is data in local storage, the page will be rendered based on that data, if not, the page will be rendered using the default settings. This ensures that when switching between pages, the page state can automatically synchronize from local storage to the URL

**Comment by FedericoTartarini** [comment]
Let's discuss this in detail during the upcoming meeting.
