### ISSUE TITLE
Finalise Custom Ensable code

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/comfort-dash#25]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/6aadc906-8fa5-4eb3-ac3b-5bb15c16c20f">

Hi could you please finalise this component by using the values from the old version of the CBE thermal comfort tool and entering them in here. https://github.com/CenterForTheBuiltEnvironment/comfort-dash/blob/3843f071e05a101603b04e43ce51f28620e29bfa/components/input_environmental_personal.py#L24

We should also implement the functionality that when the user press submit then the clo value gets updated.

**Comment by Ruixin126** [comment]
Please check the pull request and give me some feedback

**Comment by FedericoTartarini** [comment]
there is a very major issue in the code now. When someone enters a value of met < 1 the value is shown in the inputs but the store is not updated and the calculation is done using a met value of 1. This is very bad, we should limit the input to the range as a function of the model selected.

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/3465dd8d-b556-4386-b254-0b7d8e8f2145">

**Comment by FedericoTartarini** [comment]
@Ruixin126 could you please reply to this issue?

**Comment by Ruixin126** [comment]
I think the bug is not belong to me, and my code is not include the part of what you said, the bugs should be create a new issue, and for this bug, echo will be fix the bugs, he may give you more specifics.

**Comment by FedericoTartarini** [comment]
okay
