### ISSUE TITLE
Check Clima codebase

### ISSUE THREAD

**Issue by t-kramer** [CenterForTheBuiltEnvironment/comfort-dash#3]
Familiarize yourself with the [Clima codebase](https://github.com/CenterForTheBuiltEnvironment/clima). Assess how the project is structured and identify aspects we can improve for the Comfort tool.

Important considerations when building an application is:
* use components to avoid code duplications. All the components should be save in the `components` folder
* use classes rather than dictionaries
* save the state of the application in one single location
* use dash-mantine-component rather that re-creating your component
* the application should be working both on mobile and desktop

**Comment by karlliu666** [comment]
Hi client, I 've already  learned the outcome of completed project compare to Clima codebase.

**Comment by CharlieJiangJC** [comment]
Hello client, I 've also already learned the project compared to Clima codebase.

**Comment by FedericoTartarini** [comment]
Great. In future, please note that there is no need to comment that you have completed a task. Simply close the issue instead.
