### ISSUE TITLE
Develop ideas for main UI plots

### ISSUE THREAD

**Issue by t-kramer** [CenterForTheBuiltEnvironment/comfort-dash#4]
For the new version of the Comfort Tool, we want to include most functions/models listed [here](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html). This will go far beyond the current capabilities, which means that we also need to think about plots visualizing the results of the newly introduced functions in the main UI.

Go through the listed functions and develop ideas for visuals, ideally using Plotly.

**Comment by Yannnnnnny** [comment]
Wǒ kàn dào nǐ zài chart.Py zhōng dìngyìle yīgè example, xiànzài wǒmen zuò chūle yīgè ‘adaptive ASHAREA’ de ànlì, bù zhīdào wǒmen yīnggāi shàngchuán dào nǎlǐ ne
71 / 5,000
I saw that you defined an example in chart.py. Now we have made an 'adaptive ASHAREA' case. I don't know where we should upload it.

**Comment by Yannnnnnny** [comment]
I saw that you defined an example in ‘charts.py’. Now we have made a visualization of 'adaptive ASHAREA' case. I don't know where we should upload it.

**Comment by t-kramer** [comment]
@Yannnnnnny Open a branch for this issue and add your chart to the charts.py module. Before you submit a pull request, please share a screenshot of the visualization here, so I can take a look.

Alternatively, since you'll be developing and testing more charts, you can also create a notebook (on the new branch) for all of them and add the newly developed plots to the charts module whenever we think they are ready.

**Comment by FedericoTartarini** [comment]
@Yannnnnnny I like the suggestion of creating a notebook in which you can show us all the charts you are working on, this will enable you to focus on the chart code and not on the Dash code. Moreover it will enable us to quickly review your work and will create less merge errors.

**Comment by Yannnnnnny** [comment]
thanks for your suggestion, I will create a notebook for visualization.

**Comment by Yannnnnnny** [comment]
sorry to bother you, we haven't find the mature chart model in plotly for Psychrometric Chart, can we use other libraries?
if we can't, could we use numpy help to draw the chart?
![WechatIMG207](https://github.com/user-attachments/assets/b3544984-0ae2-4c0f-85ac-8089ca5268d6)

**Comment by FedericoTartarini** [comment]
You can recreate the chart simply by plotting lines as we did in the CBE Clima too. The clima tool code is [here](https://github.com/CenterForTheBuiltEnvironment/clima/blob/main/my_project/tab_psy_chart/app_psy_chart.py). However, do not simply copy and paste the code since we need to simplify it.

**Comment by Yannnnnnny** [comment]
thank you!!

**Comment by FedericoTartarini** [comment]
very happy to help :), but please in future no need to write thank you so we can reduce the number of notifications all the team members in this issue receive.

**Comment by black6pepper** [comment]
i been made a few visualization
and i wanna hear some advice from you
firstly is the adaptive method of EN 16798
The one on the left is the one I made and the one on the right is the original image.

![23bbed795e63ed18ec73b19d653f624](https://github.com/user-attachments/assets/bbd21576-270e-4458-88f8-fc4951a7cdc0)

Then there's the psychrometric char of EN-16798.
![image](https://github.com/user-attachments/assets/6cceb8d8-7246-40e5-9008-5085ab9626df)
I drew this picture and added a different hover function to show the value of the current point when the mouse moves to a certain place.
it followed by my comparison chart
![image](https://github.com/user-attachments/assets/dfd0fbd4-703f-4de7-9940-1b416425aabe)
Could you please give me a little advice so that I can do a better job?
thank you very much

**Comment by t-kramer** [comment]
@black6pepper That's a good start. The adaptive chart looks very much like we want it to be and with some minor tweaks (font sizes, alpha values, layout, etc.) it'll be fine. For the psychrometric chart, you should try to get closer to the template from the original tool. Do you have any particular problems creating the psychrometric chart?

Also, I'd like to see the code and provide more detailed comments there. Can you share it in the repository? Ideally we use notebooks until we are satisfied with the chart.

**Comment by FedericoTartarini** [comment]
I agree with all the comments from Toby.  @black6pepper This is a very good start, however, we need to make sure that the layout of the charts is consistent, for exmaple:
* the legend is always in the same location
* we always display the key data of the cursor location
* the font size is consistent
* the labels looks the same
* the background is plain

Sometimes the chart in the CBE thermal comfort tool are not perfect and need to be improved, hence, before recreating them please have a quick chat with me and @t-kramer. Please also share the code with us and not just screenshots. I am very happy to see some progress on this.

**Comment by t-kramer** [comment]
@black6pepper @Yannnnnnny Can you please start sharing your ideas for the plots using a notebook? I'd like to help you, but need to see the code.
