### ISSUE TITLE
When IP is selected the results do not update

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/comfort-dash#43]
When the IP units are selected the results do not update.

To recreate the issue just click on IP units toggle and try to change the inputs.

**Comment by Ruixin126** [comment]
I found the calculation actually still using the SI Units to get the result and charts, and the value don't update to the MyStores when we change the value if togger to IP Units, do we still need to store the converted value in the MyStores, but when runs the chart and gets the result uses SI mode for calculation, So do we need to convert the value in charts and result file?

**Comment by Ha02hen** [comment]
Fixed the issue where data was not being stored in local storage when switching units. Refer to #38 for details on the pull request.
