### ISSUE TITLE
Feature Request: Store Only SI Variables in Local Storage

### ISSUE THREAD

**Issue by Ha02hen** [CenterForTheBuiltEnvironment/comfort-dash#44]
### Data Storage Approach
I think it might be more appropriate to store data based on units. From the current code implementation (as shown in the image), this approach handles unit conversion for labels, descriptions, and values.This part of the code handles unit conversion for label, description, and value. If we need to handle the value separately outside of the main code, it would require adding an additional method specifically for processing the value, and the ` convert_units() ` method would no longer handle value conversion.
![image](https://github.com/user-attachments/assets/f0f4402e-cc47-4937-bc36-4b619f3d93b3)
### Current Code Logic
Additionally, the code segment in the image processes the content of the input fields. When the unit changes, the values are retrieved from here. Our current logic stores these values in the URL and updates the input fields based on URL changes.
![image](https://github.com/user-attachments/assets/44c93154-620c-4892-a6f4-ef7ea3afd7bd)
![image](https://github.com/user-attachments/assets/7ddcff3d-26dc-46ac-a629-0f0d6daa4d7b)
![image](https://github.com/user-attachments/assets/d44d9a7f-1e89-4c97-a6f1-95c7f8086c8e)
### Impact of Storing Only SI Variables
If we only store SI variables in local storage, the code logic will change to: when the unit is switched, the content in the input fields will change, but the data in local storage and the URL will remain unchanged. This would significantly increase the complexity of the existing code.
### Proposed Solution for Simplifying Code Expansion
To simplify future code expansion, we could add a units parameter to the relevant methods, allowing for easy conversion of data formats. This would require modifying only a single part of the code.

**Comment by FedericoTartarini** [comment]
Okay so we can implement your suggestion and store the values in the unit as selected in the application.
