### ISSUE TITLE
Design, test and Implement the compare page

### ISSUE THREAD

**Issue by Ruixin126** [CenterForTheBuiltEnvironment/comfort-dash#47]
We will Implement the Compare page next week, and now redesign and test the compare module on the current page. If you have more ideas or need additional features, please comment below.
Now adjust the parameters in the left two columns wil reflect to the right chart, and the value, already stored in mystore, which will be tracked in lower right corner, the design and testing of the result in the top right corner will also continue, and any updates will be written here:
![image](https://github.com/user-attachments/assets/0d713310-1487-4fd2-8955-e9ed757ae906)
Apply dropdown box to metabolic rate and clothing level
![image](https://github.com/user-attachments/assets/b29bafb1-abc1-43f5-9f50-1bbc9add7633)

**Comment by Marcusxixi** [comment]
I add another result for the compare function and change the color for different result
![image](https://github.com/user-attachments/assets/c369d295-dbeb-4e53-91d9-e9eb8246813b)

**Comment by Marcusxixi** [comment]
@FedericoTartarini If you think it's okay for this design, we will make a pull request for that

**Comment by FedericoTartarini** [comment]
Amazing work, please create the pull request for this
