### ISSUE TITLE
Recreate header and footer

### ISSUE THREAD

**Issue by t-kramer** [CenterForTheBuiltEnvironment/comfort-dash#6]
Recreate the CBE header and footer using Dash components.

**Reminder:** The header and footer design can be found on [Miro](https://miro.com/app/board/uXjVKpPJvxE=/?share_link_id=841990080046) and another CBE [repo](https://github.com/CenterForTheBuiltEnvironment/cbe-tool-template).

**Comment by t-kramer** [comment]
@Marcusxixi @ZhouTongworking Here a few comments on the current implementation of header and footer.

First of all, thanks for your work so far. It looks great! However, there are some minor things you should work on.

### Dynamic behavior, Header
I don't like the current behavior for mobile/smaller screens. Also, we don't want the title to go over four lines, so make the break early enough.

![Screenshot 2024-09-09 at 7 54 23 PM](https://github.com/user-attachments/assets/d64b7132-4bf9-4b77-ba8b-ce1c758aeab5)

![Screenshot 2024-09-09 at 7 54 09 PM](https://github.com/user-attachments/assets/b1b1b8d2-0c22-45e6-af8d-a00f59f537d3)

I'd prefer this behavior where the three containers for logo, title and navbar a simple stacked vertically and centered horizontally. I think it's cleaner.

<img width="563" alt="Screenshot 2024-09-09 at 8 03 52 PM" src="https://github.com/user-attachments/assets/961310ba-e08d-4baf-a1c2-832510724ab3">

**Comment by t-kramer** [comment]
### Dropdown Options

I don't think we need to include all tools, it's too much. 

![Screenshot 2024-09-09 at 7 58 47 PM](https://github.com/user-attachments/assets/ca0b86ec-8e0e-48ff-8dbe-964bc044cb4b)

I suggest to focus on these four:

![Screenshot 2024-09-09 at 7 59 33 PM](https://github.com/user-attachments/assets/1d23a61d-cfc6-4979-8823-4f2a69fb0e02)

**Comment by t-kramer** [comment]
### Dynamic behavior, Footer

Similar to the header above, I suggest some changes to the dynamic behavior of the footer for smaller screens. This doesn't look clean.

![Screenshot 2024-09-09 at 7 52 38 PM](https://github.com/user-attachments/assets/d072d3f7-d71d-4491-bd67-ca4b871a75db)

Maybe this is a better layout. I'm not 100% convinced (open for your ideas), but it's definitely better than above and can be simply implemented by using vertical stacking and horizontal centering of the containers.

<img width="605" alt="Screenshot 2024-09-09 at 8 16 55 PM" src="https://github.com/user-attachments/assets/da0de728-de6c-47ba-a2e2-82b911259fce">

**Comment by t-kramer** [comment]
- [ ] Adjust header
- [ ] Reduce dropdown
- [ ] Adjust footer

**Comment by FedericoTartarini** [comment]
@Marcusxixi I approved your Pull request, however, please fix the following.
The logo in small screens should be smaller and on the left it should be on the same line as the name of the tool, we should not waste important vertical space. If they do not fit on the same line you can reduce a bit the font size of the tool name.

**Comment by Marcusxixi** [comment]
> @Marcusxixi I approved your Pull request, however, please fix the following.
> 
> @t-kramer and @Marcusxixi I think that the logo in small screens should be smaller and on the left it should be on the same line as the name of the tool, we should not waste important vertical space. If they do not fit on the same line you can reduce a bit the font size of the tool name. @Marcusxixi may you implement this?

Sure
