### ISSUE TITLE
Check Comfort Dash skeleton

### ISSUE THREAD

**Issue by t-kramer** [CenterForTheBuiltEnvironment/comfort-dash#7]
Check Comfort Dash skeleton developed by Federico. Familiarise with components and config and webpage_text file.

- [x] Fork repo
- [x] check structure

**Comment by t-kramer** [comment]
@karlliu666 @lja996877259 @Jinjia-Bai @CharlieJiangJC You can start working on this.

**Comment by karlliu666** [comment]
The priciple of each selectbox using on page has already been familiar, our four people are discussing about how to achieve the parameter capture on the back end of the Dash.
