### ISSUE TITLE
CBE header and footer

### ISSUE THREAD

**Issue by t-kramer** [CenterForTheBuiltEnvironment/comfort-dash#9]
Recreate the CBE header and footer using Dash components.

**Reminder:** The header and footer design can be found on [Miro](https://miro.com/app/board/uXjVKpPJvxE=/?share_link_id=841990080046) and another CBE [repo](https://github.com/CenterForTheBuiltEnvironment/cbe-tool-template).

**Comment by Xuhui-Wang-9988** [comment]
shall we keep the current design of model selection drop down or move it to the more CBE Tools humburger button at the top-right corner?

**Comment by FedericoTartarini** [comment]
Please keep it as in the video that I shared the other day. If possible in the future also provide a screenshot with an example so it is easier to provide an answer.

**Comment by t-kramer** [comment]
@Xuhui-Wang-9988 For consistency, please also ask these questions on separate issue next time. This one is about the header and footer, your questions refer to the main tool container (between header and footer). Asking questions in the correct spots will make it easier to follow later on.

**Comment by Marcusxixi** [comment]
@t-kramer I still can not access the [repo ](https://github.com/CenterForTheBuiltEnvironment/cbe-tool-template)link show above, could you please fix this issues?

**Comment by t-kramer** [comment]
@Marcusxixi I just made the repo public. You should be able to access it now.

**Comment by Marcusxixi** [comment]
@t-kramer Here is the modified header, Is that ok?
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/0b550dca-2114-4f80-bd42-7b4e045bca5d">

**Comment by Marcusxixi** [comment]
> @t-kramer Here is the modified header, Is that ok? <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/80607854/363457854-0b550dca-2114-4f80-bd42-7b4e045bca5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjU1NDEsIm5iZiI6MTcyNTE2NTI0MSwicGF0aCI6Ii84MDYwNzg1NC8zNjM0NTc4NTQtMGI1NTBkY2EtMjExNC00ZjgwLWJkNDItN2I0ZTA0NWJjYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NGYwMTI5NzcxMDMxMzQxYWZjZDg2MjkzMjg4ZTk2MjFmYTZiZGUzZTk1NTZlYzc2YjM1YmQ1ZGJhYTM0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vum6pjqd7BXV619pOOCFbFYzRXqX1dI3u4KUxe8wNb0">

**Comment by t-kramer** [comment]
@Marcusxixi Looks good. The title would be CBE Thermal Comfort Tool.

Did you look into a mobile version as well? For that, you ideally stack (and maybe resize) the containers vertically (logo on top, then title, then navbar). The navlinks in the navbar container should also be stacked vertically. Also, it's fine to use the CBE logo as a placeholder in the header for now. But we will exchange that later.

Please also work on the footer (incl. mobile). Thank you!

**Comment by Marcusxixi** [comment]
@t-kramer Here is the mobile version of the header
![c67bb378950815f66eab008a304e4d3](https://github.com/user-attachments/assets/1e6f9a12-2d05-4325-9a9e-1a5820fb232c)
![81fc463cdee398c1de1008ad76bbfe8](https://github.com/user-attachments/assets/da9b1813-db84-4fae-963e-46e19db1722b)

**Comment by FedericoTartarini** [comment]
In my computer it does not look like in your screenshot. it looks like this. I lefted several comments in the code.

<img width="405" alt="image" src="https://github.com/user-attachments/assets/294650db-e59f-4d03-8687-9152998df065">

**Comment by t-kramer** [comment]
@Marcusxixi I just pushed some updates to the [repository](https://github.com/CenterForTheBuiltEnvironment/cbe-tool-template) containing the template layout for the header and footer. I added some basic mobile responsiveness using flexbox and breakpoints for tablets and smartphones. You can fork the repo and check the behaviour for reference. It should be simple to recreate a similar behaviour using Dash components. Feel free to make improvements if you have ideas. I'm not 100% happy myself, but at least it's clean and readable and should be a good starting point for us to narrow down the final layout.

I also changed the placeholder for the logo in the top left corner to a rectangular one (since the new logos will be rectangular). Please take this into account.

**Comment by FedericoTartarini** [comment]
Please all note that when possible always use dash mantine components never CSS. It should be a simple job since basically we can achieve that with grids and simple grids
